license_id: cc-by
methodology: Other
methodology_other: Modeled population exposure combining NHC storm forecast/observed track buffers with GDACS/ADAM exposure data
caveats: Admin1 units are identified using FieldMaps p-codes
dataset_source: OCHA Data Science storms database
package_creator: HDX Data Systems Team
private: False
maintainer: b682f6f7-cd7e-4bd4-8aa7-f74138dc6313
owner_org: 05547d2c-8430-4ce8-8e48-e3ea7e52a9a2
